name: zdeutsch

services:
  zdeutsch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zdeutsch-app
    environment:
      NODE_ENV: production
      PORT: 3030
    ports:
      - "${WEB_PORT:-80}:3030"
      - "${APP_PORT:-3030}:3030"
    restart: unless-stopped
